# Generated by ChatGPT on 2025-12-27
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stations", "0003_rename_ses_station"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForecastReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("days", models.PositiveIntegerField(default=1)),
                ("weather_source", models.CharField(blank=True, max_length=64)),
                ("recipients", models.TextField(blank=True)),
                ("file", models.FileField(upload_to="forecast_reports/")),
                ("error", models.TextField(blank=True)),
                ("station", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="forecast_reports", to="stations.station")),
            ],
        ),
    ]
