# Generated by ChatGPT on 2025-12-27
import datetime

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForecastSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("enabled", models.BooleanField(default=False)),
                ("run_time", models.TimeField(default=datetime.time(6, 0))),
                ("days", models.PositiveIntegerField(default=1)),
                ("providers", models.CharField(blank=True, max_length=128)),
                ("emails", models.TextField(blank=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("station", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="forecast_schedules", to="stations.station")),
            ],
        ),
    ]
