# Generated by ChatGPT on 2025-12-27
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_forecastschedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="forecastschedule",
            name="start_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
