# Generated by ChatGPT on behalf of user request to adjust station capacity naming.
import re
from django.db import migrations


def forward_update_capacity(apps, schema_editor):
    Station = apps.get_model("stations", "Station")
    pattern = re.compile(r"10\\s*mw", re.IGNORECASE)

    for station in Station.objects.all():
        name_updated = False
        if pattern.search(station.name or ""):
            station.name = pattern.sub("8.8MW", station.name)
            name_updated = True

        capacity_updated = False
        if station.capacity_mw == 10:
            station.capacity_mw = 8.8
            capacity_updated = True

        if name_updated or capacity_updated:
            station.save(update_fields=["name", "capacity_mw"])


def reverse_update_capacity(apps, schema_editor):
    Station = apps.get_model("stations", "Station")
    pattern = re.compile(r"8\\.8\\s*mw", re.IGNORECASE)

    for station in Station.objects.all():
        name_updated = False
        if pattern.search(station.name or ""):
            station.name = pattern.sub("10MW", station.name)
            name_updated = True

        capacity_updated = False
        if station.capacity_mw == 8.8:
            station.capacity_mw = 10
            capacity_updated = True

        if name_updated or capacity_updated:
            station.save(update_fields=["name", "capacity_mw"])


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            forward_update_capacity,
            reverse_update_capacity,
        ),
    ]
