# Generated by Django 5.2.8 on 2025-12-12 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='azimuth_deg',
            field=models.FloatField(default=180.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(360.0)]),
        ),
        migrations.AddField(
            model_name='station',
            name='capacity_ac_kw',
            field=models.FloatField(default=1000.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='station',
            name='capacity_dc_kw',
            field=models.FloatField(default=1000.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='station',
            name='losses_total_pct',
            field=models.FloatField(default=10.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(40.0)]),
        ),
        migrations.AddField(
            model_name='station',
            name='pr_default',
            field=models.FloatField(default=0.88, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='station',
            name='tilt_deg',
            field=models.FloatField(default=30.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='station',
            name='latitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='station',
            name='longitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
    ]
