# Generated by ChatGPT on behalf of user request to adjust station capacity naming.
import re
from django.db import migrations


def forward_update_capacity(apps, schema_editor):
    Station = apps.get_model("stations", "Station")
    pattern = re.compile(r"10\s*mw", re.IGNORECASE)

    for station in Station.objects.all():
        updated_fields = []
        if pattern.search(station.name or ""):
            station.name = pattern.sub("8.8MW", station.name)
            updated_fields.append("name")

        if station.capacity_mw == 10:
            station.capacity_mw = 8.8
            updated_fields.append("capacity_mw")

        if updated_fields:
            station.save(update_fields=updated_fields)


def reverse_update_capacity(apps, schema_editor):
    Station = apps.get_model("stations", "Station")
    pattern = re.compile(r"8\.8\s*mw", re.IGNORECASE)

    for station in Station.objects.all():
        updated_fields = []
        if pattern.search(station.name or ""):
            station.name = pattern.sub("10MW", station.name)
            updated_fields.append("name")

        if station.capacity_mw == 8.8:
            station.capacity_mw = 10
            updated_fields.append("capacity_mw")

        if updated_fields:
            station.save(update_fields=updated_fields)


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            forward_update_capacity,
            reverse_update_capacity,
        ),
    ]
