# Generated by Django 5.2.8 on 2026-02-13 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0006_organizationinvitation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='organizationinvitation',
            new_name='stations_or_organiz_41d0d8_idx',
            old_name='stations_or_organiz_14b6a7_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationinvitation',
            new_name='stations_or_invited_ac3bcf_idx',
            old_name='stations_or_invited_8e7f65_idx',
        ),
    ]
