# Generated by Django 5.2.8 on 2026-02-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0007_rename_stations_or_organiz_14b6a7_idx_stations_or_organiz_41d0d8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='subscription_status',
            field=models.CharField(
                choices=[
                    ('trialing', 'Trialing'),
                    ('active', 'Active'),
                    ('past_due', 'Past due'),
                    ('canceled', 'Canceled'),
                ],
                default='trialing',
                max_length=16,
            ),
        ),
    ]
