# Generated by Codex on 2026-06-09.

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0019_station_irradiation_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="tracker_axis_tilt",
            field=models.FloatField(
                default=0.0,
                help_text="Наклон оси одноосевого трекера, градусы.",
                validators=[MinValueValidator(0.0), MaxValueValidator(90.0)],
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="tracker_axis_azimuth",
            field=models.FloatField(
                default=0.0,
                help_text="Азимут оси одноосевого трекера, градусы.",
                validators=[MinValueValidator(0.0), MaxValueValidator(360.0)],
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="tracker_max_angle",
            field=models.FloatField(
                default=30.0,
                help_text="Максимальный угол поворота одноосевого трекера.",
                validators=[MinValueValidator(0.0), MaxValueValidator(90.0)],
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="tracker_gcr",
            field=models.FloatField(
                default=0.4,
                help_text="Ground coverage ratio для backtracking одноосевого трекера.",
                validators=[MinValueValidator(0.01), MaxValueValidator(1.0)],
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="tracker_backtrack",
            field=models.BooleanField(
                default=True,
                help_text="Использовать backtracking при расчёте POA через pvlib.",
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="tracker_poa_model",
            field=models.CharField(
                default="perez",
                help_text="Модель sky diffuse для pvlib GHI→POA (по умолчанию perez).",
                max_length=32,
            ),
        ),
    ]
