# Generated by Codex on 2026-06-09.

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0020_station_tracker_pvlib_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="tracker_albedo",
            field=models.FloatField(
                default=0.20,
                help_text="Albedo для pvlib GHI→POA одноосевого трекера.",
                validators=[MinValueValidator(0.0), MaxValueValidator(1.0)],
            ),
        ),
    ]
