ar_layers: &id001 []
compute_components_flag: false
config_ar: !!python/object:neuralprophet.configure.AR
  ar_layers: *id001
  ar_reg: null
  n_lags: 0
  reg_lambda: null
config_events: null
config_holidays: null
config_lagged_regressors: null
config_normalization: !!python/object:neuralprophet.configure.Normalization
  global_data_params: !!python/object/apply:collections.OrderedDict
  - - - ds
      - &id004 !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:pandas._libs.tslibs.timedeltas._timedelta_unpickle
        - 90820800000000000
        - 10
        shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
        - 1672545600000000000
        - null
        - null
        - 10
    - - y
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - &id002 !!python/object/apply:numpy.dtype
          args:
          - f8
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - !!binary |
          4QuTqYJpIkA=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          FR3J5T80FsA=
    - - Irradiation
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          AAAAAADbkEA=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          AAAAAAAAAAA=
    - - Air_Temp
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          mpmZmZnJUUA=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          zczMzMxMPsA=
    - - PV_Temp
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          bhKDwMrFVUA=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          zczMzMxMPsA=
    - - hour_sin
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          5J0/M09Q+z8=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          yTt/Zp6g5r8=
    - - month_sin
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          AAAAAAAAAEA=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          AAAAAAAA8L8=
    - - is_clear
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - &id003 !!python/object/apply:numpy.dtype
          args:
          - i8
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - !!binary |
          AQAAAAAAAAA=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id003
        - !!binary |
          AAAAAAAAAAA=
    - - y_expected_log
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          KrFL0c5wAkA=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          AAAAAAAAAAA=
    - - morning_peak_boost
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - *id003
        - !!binary |
          AQAAAAAAAAA=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id003
        - !!binary |
          AAAAAAAAAAA=
    - - overdrive_flag
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - *id003
        - !!binary |
          AQAAAAAAAAA=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id003
        - !!binary |
          AAAAAAAAAAA=
    - - midday_penalty
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - *id003
        - !!binary |
          AQAAAAAAAAA=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id003
        - !!binary |
          AAAAAAAAAAA=
    - - is_morning_active
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - *id003
        - !!binary |
          AQAAAAAAAAA=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id003
        - !!binary |
          AAAAAAAAAAA=
    - - sun_elev_deg
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          hKu8L3C3XUA=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          2Y2rC6qkSsA=
    - - low_sun_flag
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - *id003
        - !!binary |
          AQAAAAAAAAA=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id003
        - !!binary |
          AAAAAAAAAAA=
  global_normalization: true
  global_time_normalization: true
  local_data_params: !!python/object/apply:collections.OrderedDict
  - - - __df__
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - *id004
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                4QuTqYJpIkA=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                FR3J5T80FsA=
          - - Irradiation
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                AAAAAADbkEA=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                AAAAAAAAAAA=
          - - Air_Temp
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                mpmZmZnJUUA=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                zczMzMxMPsA=
          - - PV_Temp
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                bhKDwMrFVUA=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                zczMzMxMPsA=
          - - hour_sin
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                5J0/M09Q+z8=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                yTt/Zp6g5r8=
          - - month_sin
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                AAAAAAAAAEA=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                AAAAAAAA8L8=
          - - is_clear
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id003
              - !!binary |
                AQAAAAAAAAA=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id003
              - !!binary |
                AAAAAAAAAAA=
          - - y_expected_log
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                KrFL0c5wAkA=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                AAAAAAAAAAA=
          - - morning_peak_boost
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id003
              - !!binary |
                AQAAAAAAAAA=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id003
              - !!binary |
                AAAAAAAAAAA=
          - - overdrive_flag
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id003
              - !!binary |
                AQAAAAAAAAA=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id003
              - !!binary |
                AAAAAAAAAAA=
          - - midday_penalty
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id003
              - !!binary |
                AQAAAAAAAAA=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id003
              - !!binary |
                AAAAAAAAAAA=
          - - is_morning_active
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id003
              - !!binary |
                AQAAAAAAAAA=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id003
              - !!binary |
                AAAAAAAAAAA=
          - - sun_elev_deg
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                hKu8L3C3XUA=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                2Y2rC6qkSsA=
          - - low_sun_flag
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id003
              - !!binary |
                AQAAAAAAAAA=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id003
              - !!binary |
                AAAAAAAAAAA=
  normalize: auto
  unknown_data_normalization: false
config_regressors: !!python/object:neuralprophet.configure.ConfigFutureRegressors
  d_hidden: 4
  model: linear
  num_hidden_layers: 2
  regressors: !!python/object/apply:collections.OrderedDict
  - - - Irradiation
      - !!python/object:neuralprophet.configure.Regressor
        mode: additive
        normalize: minmax
        reg_lambda: null
    - - Air_Temp
      - !!python/object:neuralprophet.configure.Regressor
        mode: additive
        normalize: minmax
        reg_lambda: null
    - - PV_Temp
      - !!python/object:neuralprophet.configure.Regressor
        mode: additive
        normalize: minmax
        reg_lambda: null
    - - hour_sin
      - !!python/object:neuralprophet.configure.Regressor
        mode: additive
        normalize: minmax
        reg_lambda: null
    - - month_sin
      - !!python/object:neuralprophet.configure.Regressor
        mode: additive
        normalize: minmax
        reg_lambda: null
    - - is_clear
      - !!python/object:neuralprophet.configure.Regressor
        mode: additive
        normalize: minmax
        reg_lambda: null
    - - y_expected_log
      - !!python/object:neuralprophet.configure.Regressor
        mode: additive
        normalize: minmax
        reg_lambda: null
    - - morning_peak_boost
      - !!python/object:neuralprophet.configure.Regressor
        mode: additive
        normalize: minmax
        reg_lambda: null
    - - overdrive_flag
      - !!python/object:neuralprophet.configure.Regressor
        mode: additive
        normalize: minmax
        reg_lambda: null
    - - midday_penalty
      - !!python/object:neuralprophet.configure.Regressor
        mode: additive
        normalize: minmax
        reg_lambda: null
    - - is_morning_active
      - !!python/object:neuralprophet.configure.Regressor
        mode: additive
        normalize: minmax
        reg_lambda: null
    - - sun_elev_deg
      - !!python/object:neuralprophet.configure.Regressor
        mode: additive
        normalize: minmax
        reg_lambda: null
    - - low_sun_flag
      - !!python/object:neuralprophet.configure.Regressor
        mode: additive
        normalize: minmax
        reg_lambda: null
config_seasonality: !!python/object:neuralprophet.configure.ConfigSeasonality
  computation: fourier
  condition_name: null
  daily_arg: true
  daily_global_local: auto
  global_local: global
  mode: additive
  periods: !!python/object/apply:collections.OrderedDict
  - - - daily
      - !!python/object:neuralprophet.configure.Season
        arg: true
        condition_name: null
        global_local: global
        period: 1
        resolution: 6
  reg_lambda: 0
  seasonality_local_reg: false
  weekly_arg: false
  weekly_global_local: auto
  yearly_arg: false
  yearly_global_local: auto
config_train: !!python/object:neuralprophet.configure.Train
  batch_size: 64
  epochs: 400
  lambda_delay: 200
  learning_rate: 0.2
  loss_func: !!python/object:torch.nn.modules.loss.MSELoss
    _backward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _buffers: {}
    _forward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
    - []
    _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
    - []
    _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
    - []
    _is_full_backward_hook: null
    _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _modules: {}
    _non_persistent_buffers_set: !!set {}
    _parameters: {}
    _state_dict_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    reduction: none
    training: true
  loss_func_name: MSELoss
  lr_finder_args: {}
  n_data: 20734
  newer_samples_start: 0.0
  newer_samples_weight: 2
  optimizer: !!python/name:torch.optim.adamw.AdamW ''
  optimizer_args:
    weight_decay: 0.001
  quantiles:
  - 0.5
  reg_delay_pct: 0.5
  reg_lambda_trend: null
  scheduler: !!python/name:torch.optim.lr_scheduler.OneCycleLR ''
  scheduler_args:
    anneal_strategy: cos
    div_factor: 10.0
    final_div_factor: 10.0
    pct_start: 0.3
    three_phase: true
  trend_reg_threshold: null
config_trend: !!python/object:neuralprophet.configure.Trend
  changepoints: null
  changepoints_range: 0.8
  growth: linear
  n_changepoints: 10
  trend_global_local: global
  trend_local_reg: false
  trend_reg: 0
  trend_reg_threshold: null
id_list:
- __df__
lagged_reg_layers: []
max_lags: 0
meta_used_in_model: false
metrics:
  MAE:
  - MeanAbsoluteError
  - {}
  RMSE:
  - MeanSquaredError
  - squared: false
n_forecasts: 1
n_lags: 0
num_seasonalities_modelled: 1
num_seasonalities_modelled_dict: !!python/object/apply:collections.OrderedDict
- - - yearly
    - 1
  - - weekly
    - 1
  - - daily
    - 1
num_trends_modelled: 1
