# Generated by Django 5.2.8 on 2025-11-18 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('irradiation', models.FloatField(blank=True, null=True)),
                ('air_temp', models.FloatField(blank=True, null=True)),
                ('pv_temp', models.FloatField(blank=True, null=True)),
                ('power_kw', models.FloatField(blank=True, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='stations.station')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['station', 'timestamp'], name='solar_solar_station_ded79b_idx')],
            },
        ),
    ]
