# Generated by Django 5.2.8 on 2025-11-24 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0001_initial'),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('pred_np', models.FloatField()),
                ('pred_xgb', models.FloatField()),
                ('pred_heur', models.FloatField()),
                ('pred_final', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='stations.station')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['station', 'timestamp'], name='solar_solar_station_8a625a_idx')],
                'unique_together': {('station', 'timestamp')},
            },
        ),
    ]
