# Generated by Django 5.2.8 on 2025-12-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0002_solarforecast'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarforecast',
            name='air_temp_fc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solarforecast',
            name='cloudcover_fc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solarforecast',
            name='humidity_fc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solarforecast',
            name='irradiation_fc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solarforecast',
            name='precip_fc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solarforecast',
            name='wind_speed_fc',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
