# Generated by Django 5.2.8 on 2025-12-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0003_solarforecast_air_temp_fc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarforecast',
            name='pred_final',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solarforecast',
            name='pred_heur',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solarforecast',
            name='pred_np',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solarforecast',
            name='pred_xgb',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
