# Generated by ChatGPT on 2025-02-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar", "0004_alter_solarforecast_pred_final_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="solarforecast",
            name="snowfall_fc",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="solarforecast",
            name="snowdepth_fc",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="solarforecast",
            name="weather_code_fc",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="solarforecast",
            name="auto_snow_flag",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="solarforecast",
            name="auto_fog_flag",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="solarforecast",
            name="auto_winter_factor",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="solarforecast",
            name="manual_snow_factor",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="solarforecast",
            name="winter_factor_applied",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
