# Generated by Django 5.2.8 on 2026-02-13 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0007_solarrecord_history_scope'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='solarforecast',
            new_name='solar_solar_station_4bfd33_idx',
            old_name='solar_solar_station_d55313_idx',
        ),
        migrations.RenameIndex(
            model_name='solarrecord',
            new_name='solar_solar_station_ba022a_idx',
            old_name='solar_solar_station_11d137_idx',
        ),
    ]
