# Generated by Codex on 2026-05-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar", "0008_rename_solar_solar_station_d55313_idx_solar_solar_station_4bfd33_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="solarforecast",
            name="pred_final_raw",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="solarforecast",
            name="guardrail_reason",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
