# Generated by Codex on 2026-06-09.

from django.db import migrations


class Migration(migrations.Migration):
    """Merge the two 0009 solar migration branches.

    The guardrail fields and the split GHI/POA history fields were added in
    separate 0009 migrations. Without this merge Django stops with conflicting
    leaf nodes before it can apply later app migrations, including
    stations.0019_station_irradiation_type.
    """

    dependencies = [
        ("solar", "0009_solarforecast_guardrail_fields"),
        ("solar", "0009_solarrecord_irradiation_ghi_poa"),
    ]

    operations = []
