# Generated by Codex on 2026-06-09.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar", "0010_merge_guardrail_and_irradiation"),
    ]

    operations = [
        migrations.AddField(model_name="solarforecast", name="poa_pvlib_fc", field=models.FloatField(blank=True, null=True)),
        migrations.AddField(model_name="solarforecast", name="dni_erbs_fc", field=models.FloatField(blank=True, null=True)),
        migrations.AddField(model_name="solarforecast", name="dhi_erbs_fc", field=models.FloatField(blank=True, null=True)),
        migrations.AddField(model_name="solarforecast", name="tracker_tilt_fc", field=models.FloatField(blank=True, null=True)),
        migrations.AddField(model_name="solarforecast", name="tracker_azimuth_fc", field=models.FloatField(blank=True, null=True)),
        migrations.AddField(model_name="solarforecast", name="forecast_np_mwh", field=models.FloatField(blank=True, null=True)),
        migrations.AddField(model_name="solarforecast", name="forecast_xgb_mwh", field=models.FloatField(blank=True, null=True)),
        migrations.AddField(model_name="solarforecast", name="forecast_ensemble_base_mwh", field=models.FloatField(blank=True, null=True)),
        migrations.AddField(model_name="solarforecast", name="hist_analog_mwh", field=models.FloatField(blank=True, null=True)),
        migrations.AddField(model_name="solarforecast", name="forecast_mwh", field=models.FloatField(blank=True, null=True)),
        migrations.AddField(model_name="solarforecast", name="forecast_method", field=models.CharField(blank=True, default="", max_length=64)),
    ]
